Update 25.01.2018 (#1)
* Data cleaning pass 1

* * Glucose data smoothing / patching before calculating variability to reduce the effects of CGM noise
* Added calculation for GVI, PGS and Total Absolute Change calculation
* Refactored the server to use Webpack for the bundle generation instead of Browserify (since browserify-express seems to not work with Node 8 and is not maintained)
* Improved caching & compression of JS and CSS resources
* If NODE_ENV="development”, don’t cache resources for more than 10 seconds & generate a report about Bundle size

* Run packaging in post install instead of runtime

* CSS bundling

* Fix templates that linked to old bundle.js location

* Removing Bower part 1

* Flot plugins

* jQuery packaging has changed, adding these to the repo

* Generate source map, use a small font subset instead of loading complex CSS / font set from Google

* Added missing icons, changed how jQuery and jQuery-UI is packaged

* Bower is gone

* Remove Crossfilter (needed by /reports/compare, which is not supported right now)

* Oops forgot package-lock.json

* Revert back to using Open Sans, but embedded

* Re-enabled Ubuntu to fix the layouts. Icon font embedded.

* Update cache busters

* Added variability measure explanations to reporting

* Finnish localization

* Fix battery icon, some tests

* Added app cache manifest to speed things further

* Launch PNG was missing

* Return 404 on app cache request when in development mode, added bold weight Ubuntu

* Formatting improvements to app.js

* Added sync-exec in an attempt to appease Azure

* Added --scripts-prepend-node-path to Azure deploy script

* IT Language

* update language.js

update Russian translation

* RO update August, 27th - 2017

RO update

* Trigger app on DOM ready event (as recommended by HTML5 spec). Detect if app is completely offline, auto-reload if needed.

* Better looking loader screen, prevent CSS blocking

* Use ejs to render the app cache and cache buster tokens

* Forgot cache buster generator script

* Image had ugly artifacts

* Upgrade Travis to build with Node 8.4, update package.json to 8.4

* Doh, 8.1.4 is the latest version of Node available in Azure

* Added note on configuring Azure to README

* Separate messages for loading the client and connecting to server

* Hide loader on auth fail

* Support both node 8.1.4 (Azure) and node 8.4.0 (Heroku).

Make sure travis builds / tests both versions. Got this syntax from: https://github.com/SAP/chevrotain/commit/cedbffd3261a4f2bfe142ea11d62b9af4fd8d0cb and https://docs.microsoft.com/en-us/azure/nodejs-specify-node-version-azure-apps

* Unit tests fixed

* Increasing test timeout significantly due to Travis fails

* And add the longer timeout to Travis, too…

* Now it works

* Fixed Coverage running parameter order

* Report tests takes over 40 seconds to run in Travis, timeout increased

* More test fixes

* Increasing Travis timeouts ridiculously, we need to do something to this

* minor css fixes

* see if document ready is the problem when testing on travis

* Revert "see if document ready is the problem when testing on travis"

This reverts commit 7428040e0536b55dff48f9b72ea783c25e5afb3c.

* Update openaps.js

* Update openaps.js

* Update openaps.test.js

Test for devicestatus-entries containing the correct spelling of the word "received" instead of "recieved" in OpenAPS versions 0.6.0 and later

* change node-uuid to uuid

* npm update

* add environment variables to .travis.yml

* increase timeout to 30 secs for admintools test and change environment variables for travis

* create bundle before tests and time tests execution for travis

* Makefiles requires tabs not space. I knew that...

* change Makefile

* last try for today

* set timeout of profileeditor.test to 30 seconds

* increase timeout for profileeditor tests

* only support node 8.4.0 and drop support for node 8.1.4

* bundle creation is done by npm postinstall, so should not be called explicit.

* revert tests/fixtures/headless.js

* revert test/fixtures/headless.js (now without changing indent)

* remove env's from .travis.yml (because they might not be needed)

* Move all html files to views folder, update to use the rendered cache buster

* Fix tests to uses the view path :D

* Update README to reflect correct Node version

* Implements #2689

* Implements #2456

* One cache buster wasn't updated to dynamic form

* decrease timeouts to detect regressions faster in future

* Admintools and profileeditor test fails with 20 sec timeout. Increasing to 25 sec.
```
not ok 1 admintools "before all" hook
  Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
      at tests/admintools.test.js:177:7
      at Object.done (node_modules/benv/index.js:32:21)
      at process.nextTick (node_modules/jsdom/lib/old-api.js:347:18)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

not ok 203 Profile editor "before each" hook for "should produce some html"
  Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
      at tests/fixtures/headless.js:160:7
      at Object.module.exports.setup (node_modules/benv/index.js:24:56)
      at Function.init [as setup] (tests/fixtures/headless.js:16:10)
      at Context.<anonymous> (tests/profileeditor.test.js:94:14)
```

* optimize travis tests. see if 5 sec per test is enough (in stead of 50 sec per test)

* the following tests don't complete in 5 sec. increase timeout to 25 sec.

* increase profileeditor tests to 40 sec

* hasauth.test.js fails with 25 sec.  increasing to 40 sec

* Small fix to CGM data noise filtering

* Add Node version to DEV Azure deploy json

* Testing Node 8.1.4 for Azure

* Testing disabling heap dumps

* Update to 8.5.0 to see if that works without the problematic module

* add food to websockets

* add node env for deploy in azure

* change node to 8.5.0

* Prepare for 0.10 release

* Revert part of changes from previous merge

* Bump Nightscout version number to 0.10.1-dev

* Create issue_template.md

Adding an issue template to help solve bugs

* Fixes hourly filtering in distrubution reports, reported in #2864

* SVG dimension fix

Somehow the NONE.svg ended up with an incorrect rectangle shape; fixed
to match the aspect ratio of the other symbols.

* preserve original treatment collection

* add ZT (zero temp) prediction line

* package-lock.json

* display ZT PredBGs, and forecast tooltips

* remove extra-big tooltip target around treatments; reduce font sizes

* make R3/R4 elements into very short arcs to reposition labels

* Remove pattern regex from basal change field

Having the regex require integers means that only the numeric keypad
will pop on iOS. This prevents the entry of negative values, which is
pretty critical for temp basals.

* filter to only use actual SGV's (not rawbg's) to set the view window

* remove console.log

* Use lodash cloneDeep instead of JSON serialize/desearialize

* update Russian

* Cleanup: move cache buster token generation to /bin, remove /scripts

* Fix express-minify file cache path to reduce the memory footprint of the runtime

* Display RSSI on Loop pill

* Add missing fontello icons to main CSS

* Update version to release

* Loop RSSI fix

* One more Loop RSSI fix

* Always show RSSI

* Update dev version to 0.10.2

* exclude package-lock.json from git

* add package-lock.json to .gitignore to avoid merge conflicts

* comments

* revert font change

* Adding some test coverage for /lib/client/renderer.js

* send foods via websockets

* use websockeets instead of rest api for food

* add fat,protein,energy to food editor

* Re-enable source maps

* replace 3HR with 2HR and (default) 4HR views

* only show focusHours' worth of predictions; strip leading zero from bolus amounts

* fix spelling of focusRangeMS

* change default back to 3HR

* try larger label font: 35 instead of 25 (vs. 40)

* allow treatment bubbles to scale up past 1U/20g size

* change font size back to default in this branch

* change Bolus Snooze to Bolus IOB

* change Bolus Snooze to Bolus IOB

* back to smaller treatment dots

* handle AAPS profile switches well

* Fix URLs of [mongostring] and [autoconfigure]

* update nodejs to 8.7.0 and npm update

* do not upload temporary profiles from store

* also update nodjes used by travis from 8.5.0 to 8.7.0

* Increase timeout for careportal.test.js and pluginbase.test from 25 to 30 sec., just to be sure. I seem to work once with Node 8.7.0, but the test did a timeout once on Node 8.5.0 on Travis.

* increase timeout of admintools.test.js from 25 to 30 seconds

* pluginbase.test.js fails with 30 sec. upping to 40 sec timeout

```
not ok 188 pluginbase "before each" hook for "does stuff"
 Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
```

* update to nodejs 8.8.0 and npm update

* npm update with nodejs 8.8.0

* Update version, remove package-lock.json

* upgrade node in .nvmrc from 8.1.4 to 8.8.0
set travis container to dist: trusty and give sudo: false a try

* set sudo back to required (used for docker and mongodb commands)

* more node upgrade stuff

* Update README.md

* Fix a bug with time comparison on if-modified-since support for treatments

* Check both created_at and timestamp fields for treatments in if-modified-since logic

* Add Total daily pasal to profile editor.

Small improvoment to profile editor while geting familiar
about the code. Added a simple estimated total daily basal field.

* Bump 8.8.0 to 8.8.1

* cherry pick 33f16f4439262da2ec74c196bfa7f244910bb6fe

* merge rendering

* Revert "add package-lock.json to .gitignore to avoid merge conflicts"

This reverts commit ec2513084594c851bf9f1d00cc6f3387e75e177b.
We now use  npm-shrinkwrap.json

* fix merge errors, up version and fix test

fix merge errros by reverting views/index.html and lib/client/renderer.js,
up version in bower.json, npm-shrinkwrap.json and package.json
fix test/client.renderer.test.js

* bring back the ' U' for non-SMB's (> 1U insulin and with carbs)

* Revert "bring back the ' U' for non-SMB's (> 1U insulin and with carbs)"

This reverts commit edbf22b67e178910a76805208b4e011fa21a8ad4.

* fix typo foucusRangeMS to focusRangeMS in lib/client/chart.js

* for some reasone change from foucusRangeMS to focusRangeMS was not implemented in lib/client/index.js

This was fixed on ZT branch in https://github.com/nightscout/cgm-remote-monitor/commit/38d35398d13812cf41d43daeacd2a20c82d5b71d

* bring back the ' U' for non-SMB's (> 1U insulin and with carbs)

* More test coverage for /lib/client/renderer.js (highlightBrushPoints)

* display Sensitivity Ratio in OpenAPS pill

* add comma

* Fix SAGE pill test failing due to summer time change

* Upgrading to 8.9.0 LTS (first LTS release!) and also let travis run on both Node 8.9.0 and Node 9.0.0 (to make sure we don't introduce future problems with Node 9.0.0).
Node 8.9.0 LTS will be the recommended version.

* Drop building with nodejs 9.0.0 for now. Once NodeJS v10 almost appears were gonna test against that version.

* Update German translation

* Update German translation

* added dutch translations

* Update Loop pill RSSI (#3034)

* Update package.json

* update package.json

* Update loop.js

* test

* add BLE RSSI

* add BLE RSSI

* update RSSI time stamp

* update Loop RSSI reporting

* update Loop RSSI reporting

* show RSSI and pumpRSSI in Loop pill, if available

* update Loop pill RSSI

* Update RSSI in Loop pill

* Upgrade to node 8.9.1 and npm update and some dutch translation fixes (#3037)

* upgrade to node 8.9.1

* further improve dutch language

* remove duplicate dutch line Filter

* remove dutch language.js record that was defined two times

* fix duplicate german language record

* reapply npm-shrinkwrap.json to fix unit tests

* another try to get a proper npm-shrinkwrap.json

* shorten minutes ago in dutch to improve formatting of status pills

* deviceInfo.recent null check (#3048)

* add root mean squared out of range metric (#3045)

* Add recommended bolus and eventual BG to Loop pill (#3040)

* Update package.json

* update package.json

* Update loop.js

* test

* add BLE RSSI

* add BLE RSSI

* update RSSI time stamp

* update Loop RSSI reporting

* update Loop RSSI reporting

* show RSSI and pumpRSSI in Loop pill, if available

* update Loop pill RSSI

* Update RSSI in Loop pill

* Add recommended bolus to Loop pill

* Add eventual BG to Loop pill

* Update test for Loop pill with eventual BG

* Update test for Loop pill with eventual BG

* Update bgclock.html (#3039)

* Update index.html

* Update index.html

* Update index.html

* Update index.html

Remove alarms.

* Update index.html

* Update index.html

Removed alarms:

Line 669 & 670
            <audio src="audio/alarm.mp3" preload="auto" loop="true" class="alarm mp3" type="audio/mp3"></audio>
	    <audio src="audio/alarm2.mp3" preload="auto" loop="true" class="urgent alarm2 mp3" type="audio/mp3"></audio>

* Add Trend Arrow

Add Trend Arrow to glucose value

* Update index.html

* Update version, improvements to glucose distribution filtering

* fix reports (#3078)

* fix profile functions

* fix loading of profile switch treatments

* Shrinkwrap update

* Downgrade npm to fix deployment issues

* Smarter formatting based on amount of data (#3086)

* Smarter formatting based on amount of data, to make sure the rendering works for both SMB and non-SMB users

* Move comment to where it belongs, changed math so first 10 treatments don't reduce scaling

*  better rendering of treatments with duration (#3082)

* fix profile functions

* fix loading of profile switch treatments

* better rendering treatments with duration

* * Update Finnish localization
* Change SMB visualization to be more friendly
* Add BG Clock to navigation
* Updated release version

* 24 hour clock support for bgclock.html

* Going down to 8.9.0 for Azure

* Alternate versions in package.json

* One final change that should run on both Heroku and Azure